 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package com.credits.scapi.misc;

 public enum TokenStandardId {
   NOT_A_TOKEN,
   BASIC_STANDARD,
   EXTENSION_STANDARD,
   BASIC_TOKEN_STANDARD,
   EXTENSION_TOKEN_STANDARD
}
