 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package com.credits.scapi.v2;
 public abstract interface BasicTokenStandard extends com.credits.scapi.v1.BasicTokenStandard {
   
   public abstract  com.credits.scapi.v2.ObservableMap<? extends com.credits.scapi.v2.WalletAddress,? extends java.lang.Number> getTokenBalances();
 }