 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package com.credits.scapi.v2;
 public abstract interface MapChangeListener<K,V> {
   
   public abstract  void onChanged(com.credits.scapi.v2.MapChangeListener.EntryChange<? extends K,? extends V> entryChange);

   public class EntryChange<K, V> {}
 }
