 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package com.credits.scapi.v2;
 public abstract interface ObservableMap<K,V> extends java.util.Map<K,V> {
   
   public abstract  void addListener(com.credits.scapi.v2.MapChangeListener<? super K,? super V> listener);
   
   public abstract  void removeListener(com.credits.scapi.v2.MapChangeListener<? super K,? super V> listener);
 }