 // Failed to get sources. Instead, stub sources have been generated by the disassembler.
 // Implementation of methods is unavailable.
 package com.credits.scapi.v2;
 public abstract interface WalletAddress {
   
   public abstract java.lang.String getBase58Address();
 }